Log file created at: 2017/01/30 00:46:44
Running on machine: FEDIMSER
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
E0130 00:46:44.822448 21728 c_interface.cc:297] Throw location unknown (consider using BOOST_THROW_EXCEPTION)
Dynamic exception type: class boost::exception_detail::clone_impl<struct boost::exception_detail::error_info_injector<class std::ios_base::failure> >
std::exception::what: failed opening file: Процесс не может получить доступ к файлу, так как этот файл занят другим процессом.
: iostream stream error
E0130 00:47:10.174301  4992 c_interface.cc:297] Throw location unknown (consider using BOOST_THROW_EXCEPTION)
Dynamic exception type: class boost::exception_detail::clone_impl<struct boost::exception_detail::error_info_injector<class std::ios_base::failure> >
std::exception::what: failed opening file: Процесс не может получить доступ к файлу, так как этот файл занят другим процессом.
: iostream stream error
E0130 00:51:08.705143 20732 c_interface.cc:297] Throw location unknown (consider using BOOST_THROW_EXCEPTION)
Dynamic exception type: class boost::exception_detail::clone_impl<struct boost::exception_detail::error_info_injector<class std::ios_base::failure> >
std::exception::what: failed opening file: Процесс не может получить доступ к файлу, так как этот файл занят другим процессом.
: iostream stream error
E0130 00:52:43.482590 23604 c_interface.cc:297] Throw location unknown (consider using BOOST_THROW_EXCEPTION)
Dynamic exception type: class boost::exception_detail::clone_impl<struct boost::exception_detail::error_info_injector<class std::ios_base::failure> >
std::exception::what: failed opening file: Процесс не может получить доступ к файлу, так как этот файл занят другим процессом.
: iostream stream error
E0130 00:54:38.769556  5784 c_interface.cc:297] Throw location unknown (consider using BOOST_THROW_EXCEPTION)
Dynamic exception type: class boost::exception_detail::clone_impl<struct boost::exception_detail::error_info_injector<class std::ios_base::failure> >
std::exception::what: failed opening file: Процесс не может получить доступ к файлу, так как этот файл занят другим процессом.
: iostream stream error
E0130 00:54:58.568908 24672 c_interface.cc:297] Throw location unknown (consider using BOOST_THROW_EXCEPTION)
Dynamic exception type: class boost::exception_detail::clone_impl<struct boost::exception_detail::error_info_injector<class std::ios_base::failure> >
std::exception::what: failed opening file: Процесс не может получить доступ к файлу, так как этот файл занят другим процессом.
: iostream stream error
E0130 00:55:54.981351 19960 c_interface.cc:297] Throw location unknown (consider using BOOST_THROW_EXCEPTION)
Dynamic exception type: class boost::exception_detail::clone_impl<struct boost::exception_detail::error_info_injector<class std::ios_base::failure> >
std::exception::what: failed opening file: Процесс не может получить доступ к файлу, так как этот файл занят другим процессом.
: iostream stream error
E0130 00:56:32.082258 21144 c_interface.cc:297] Throw location unknown (consider using BOOST_THROW_EXCEPTION)
Dynamic exception type: class boost::exception_detail::clone_impl<struct boost::exception_detail::error_info_injector<class std::ios_base::failure> >
std::exception::what: failed opening file: Процесс не может получить доступ к файлу, так как этот файл занят другим процессом.
: iostream stream error
E0130 00:56:43.413419 25004 c_interface.cc:297] Throw location unknown (consider using BOOST_THROW_EXCEPTION)
Dynamic exception type: class boost::exception_detail::clone_impl<struct boost::exception_detail::error_info_injector<class std::ios_base::failure> >
std::exception::what: failed opening file: Процесс не может получить доступ к файлу, так как этот файл занят другим процессом.
: iostream stream error
